GET http://localhost:3001/api/notes
### 
DELETE http://localhost:3001/api/notes/5f0c3898b2eaa16e6843a4e3
### 
POST http://localhost:3001/api/notes  
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpcnZhbmRyZWVhIiwiaWQiOiI1ZjI5MTg4NGMwNzYyNDU0YjhiZTczMTMiLCJpYXQiOjE1OTY2MjA5MDh9.R5sqEnOhsAF14uXe-B-1smLGWce7MbgS8hwDGOCCUpU

{
    "content" : "Where are the limits of this",
    "important" : true,
    "userId": "5f29184ec0762454b8be7312"
}
###
GET http://localhost:3001/api/notes
### 
PUT http://localhost:3001/api/notes/5f0c3898b2eaa16e6843a4e3
content-type: application/json
{
    "content" : "Don't burnout, remember the 85% rule",
    "important" : true
}